/**
 * Shared resource catalog — single source of truth for both:
 *   • /resources         (public landing page, Resources.jsx)
 *   • /library           (in-app, DashboardResources.jsx)
 *
 * Any new resource gets added here ONCE. Both pages always stay in sync.
 *
 * Prior state: Resources.jsx (58 items) and DashboardResources.jsx (79 items)
 * had drifted — items unique to one weren't visible from the other. This
 * file is the merged superset with duplicates collapsed by URL.
 */

export const RESOURCES = [
  {
    id: 'assessment-guides',
    category: 'Assessment Guides',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
      </svg>
    ),
    color: '#6047EE',
    bgColor: 'rgba(96,71,238,0.08)',
    borderColor: 'rgba(96,71,238,0.2)',
    description: 'Validated screening instruments with scoring guides, severity cutoffs, and interpretation norms.',
    items: [
      { id: 'phq-9', name: 'PHQ-9 Patient Health Questionnaire', type: 'Depression Screening',
        description: 'The gold-standard 9-item depression screening tool. Includes scoring algorithm (0–27), severity bands (minimal/mild/moderate/severe), and clinical cutoff guidance.',
        url: 'https://www.phqscreeners.com/', source: 'Pfizer / PHQ Screeners' },
      { id: 'gad-7', name: 'GAD-7 Generalized Anxiety Disorder Scale', type: 'Anxiety Screening',
        description: '7-item anxiety screening tool validated for GAD, panic, social phobia, and PTSD. Scoring guide, sensitivity/specificity data, and clinical application notes.',
        url: 'https://www.phqscreeners.com/', source: 'Pfizer / PHQ Screeners' },
      { id: 'pcl-5', name: 'PCL-5 PTSD Checklist', type: 'Trauma Screening',
        description: '20-item self-report PTSD measure aligned with DSM-5. Includes diagnostic cut-scores, subscale scores for each symptom cluster, and clinician instructions.',
        url: 'https://www.ptsd.va.gov/professional/assessment/adult-sr/ptsd-checklist.asp', source: 'VA National Center for PTSD' },
      { id: 'cssrs', name: 'Columbia Suicide Severity Rating Scale (C-SSRS)', type: 'Suicide Risk Assessment',
        description: 'The most widely used structured suicide risk assessment tool. Free training, clinician-rated and self-report versions, and severity classification guidance.',
        url: 'https://cssrs.columbia.edu/', source: 'Columbia Lighthouse Project', urgent: true },
      { id: 'asrs', name: 'ASRS-v1.1 Adult ADHD Self-Report Scale', type: 'ADHD Screening',
        description: 'WHO-endorsed 18-item ADHD screener for adults. Part A (6 items) is the validated quick screener. Includes frequency scoring and clinical interpretation guide.',
        url: 'https://www.hcp.med.harvard.edu/ncs/asrs.php', source: 'Harvard Medical School / WHO' },
      { id: 'audit', name: 'AUDIT Alcohol Use Disorders Identification Test', type: 'Substance Use Screening',
        description: '10-item WHO-developed alcohol screening tool. Scoring guide (0–40) with risk zone interpretation (low risk / hazardous / harmful / probable dependence).',
        url: 'https://auditscreen.org/', source: 'World Health Organization' },
      { id: 'ids-qids', name: 'IDS / QIDS Depression Rating Scales', type: 'Depression Severity',
        description: 'Clinician-rated (IDS-C) and self-report (QIDS-SR) measures of depression severity. Sensitive to change over time — ideal for tracking treatment progress.',
        url: 'https://ids-qids.org/', source: 'UT Southwestern Medical Center' },
      { id: 'samhsa-tools', name: 'SAMHSA Evidence-Based Screening Tools', type: 'Multi-Domain Toolkit',
        description: "SAMHSA's searchable database of validated screening and assessment instruments across substance use, mental health, and co-occurring disorders.",
        url: 'https://www.samhsa.gov/resource-search/ebp', source: 'SAMHSA.gov' },
    ],
  },
  {
    id: 'clinical-protocols',
    category: 'Clinical Protocols & Interventions',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
      </svg>
    ),
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.07)',
    borderColor: 'rgba(45,212,191,0.18)',
    description: 'Evidence-based treatment protocols from leading clinical bodies. Free access where available.',
    items: [
      { id: 'cbt', name: 'Cognitive Behavioral Therapy (CBT)', type: 'Evidence-Based Protocol',
        description: 'APA Division 12 overview of CBT for depression, anxiety, and other conditions. Links to treatment manuals, training resources, and research summaries.',
        url: 'https://www.apa.org/ptsd-guideline/treatments/cognitive-behavioral-therapy', source: 'American Psychological Association' },
      { id: 'cpt', name: 'Cognitive Processing Therapy (CPT)', type: 'Trauma Protocol',
        description: 'Free CPT training and materials from MUSC. Includes the complete CPT manual (therapist and patient versions), worksheets, and online training modules.',
        url: 'https://cpt.musc.edu/', source: 'Medical University of South Carolina' },
      { id: 'cpt-prrp-manual', name: 'CPT Manual - Modified for PRRP', type: 'Trauma Protocol PDF',
        description: 'Local CPT manual adapted for PRRP use. Useful for clinician reference, session structure, stuck points, trauma themes, and CPT homework planning.',
        url: '/resources/cpt-manual-modified-for-prrp.pdf', source: 'Uploaded clinical PDF' },
      { id: 'tfcbt', name: 'Trauma-Focused CBT (TF-CBT)', type: 'Child Trauma Protocol',
        description: 'Evidence-based protocol for children and adolescents with PTSD. Includes free web-based training, implementation resources, and parent/caregiver components.',
        url: 'https://tfcbt.org/', source: 'Medical University of South Carolina' },
      { id: 'tfcbt-workbook', name: 'Your Very Own TF-CBT Workbook', type: 'Child Trauma Workbook',
        description: 'Child-friendly TF-CBT workbook with psychoeducation and skills pages clinicians can reference when planning trauma-focused work with children and adolescents.',
        url: '/resources/tf-cbt-workbook-final.pdf', source: 'Uploaded workbook PDF' },
      { id: 'dbt', name: 'Dialectical Behavior Therapy (DBT)', type: 'Skills-Based Protocol',
        description: 'Overview of DBT structure, skills modules (mindfulness, distress tolerance, emotion regulation, interpersonal effectiveness), and training pathways.',
        url: 'https://behavioraltech.org/resources/faqs/dialectical-behavior-therapy-dbt/', source: 'Behavioral Tech (Linehan Institute)' },
      { id: 'emdr', name: 'EMDR Therapy', type: 'Trauma Protocol',
        description: 'Clinical overview of Eye Movement Desensitization and Reprocessing. Includes the 8-phase protocol description, research evidence, and training directory.',
        url: 'https://www.emdria.org/about-emdr-therapy/', source: 'EMDR International Association' },
      { id: 'mi', name: 'Motivational Interviewing (MI)', type: 'Engagement Protocol',
        description: 'Core MI principles (OARS, spirit, change talk), research evidence, training resources, and the official MINT network for trained practitioners.',
        url: 'https://motivationalinterviewing.org/', source: 'Motivational Interviewing Network of Trainers' },
      { id: 'dmh-sir-note-format', name: 'DMH SIR Note Format', type: 'Documentation Template',
        description: 'Sample Situation-Intervention-Response note language for DMH-style documentation. Includes prompts for presentation, interventions, and client response.',
        url: '/resources/dmh-notes-sir-format.doc', source: 'Uploaded documentation template' },
      { id: 'pe', name: 'Prolonged Exposure Therapy (PE)', type: 'Trauma Protocol',
        description: "APA's clinical overview of PE for PTSD. Includes in vivo exposure, imaginal exposure, and processing components with evidence summary.",
        url: 'https://www.apa.org/ptsd-guideline/treatments/prolonged-exposure', source: 'American Psychological Association' },
      { id: 'exposure-therapy', name: 'Exposure Therapy Techniques', type: 'Anxiety Treatment',
        description: 'Structured guide to in-vivo and imaginal exposure for anxiety disorders, PTSD, and phobias. Includes clinical protocols and case examples.',
        url: 'https://adaa.org/finding-help/treatment/exposure-therapy', source: 'ADAA' },
      { id: 'sfbt', name: 'Solution-Focused Brief Therapy (SFBT)', type: 'Brief Intervention',
        description: 'SFBT principles, techniques, and case applications. Training resources for implementing solution-focused questions and goal-setting in sessions.',
        url: 'https://www.sfbta.org/', source: 'SFBT Academy' },
      { id: 'act', name: 'Acceptance & Commitment Therapy (ACT)', type: 'Contextual Approach',
        description: 'Evidence-based ACT resources from the Association for Contextual Behavioral Science. Theoretical foundations and clinical application guides.',
        url: 'https://contextualscience.org/', source: 'ACBS' },
    ],
  },
  {
    id: 'crisis-safety',
    category: 'Crisis & Safety Resources',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>
    ),
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.06)',
    borderColor: 'rgba(239,68,68,0.18)',
    description: 'Critical crisis lines and safety planning tools. Keep these accessible during sessions.',
    items: [
      { id: '988', name: '988 Suicide & Crisis Lifeline', type: 'Crisis Line',
        description: 'Call or text 988. 24/7 free, confidential support for people in suicidal crisis or mental health distress. Also available for clinicians consulting on cases.',
        url: 'https://988lifeline.org/', source: '988lifeline.org', urgent: true },
      { id: 'crisis-text', name: 'Crisis Text Line', type: 'Crisis Line',
        description: 'Text HOME to 741741 for free, 24/7 crisis counseling via text message. Available in US, UK, Ireland, and Canada. Useful for clients who prefer texting.',
        url: 'https://www.crisistextline.org/', source: 'crisistextline.org', urgent: true },
      { id: 'samhsa-helpline', name: 'SAMHSA National Helpline', type: 'Substance & Mental Health',
        description: '1-800-662-4357. Free, confidential, 24/7 referral and info service for mental health and substance use disorders. English and Spanish. No insurance required.',
        url: 'https://www.samhsa.gov/find-help/national-helpline', source: 'SAMHSA.gov', urgent: true },
      { id: 'miwa-lap-md', name: 'Miwa Lethality Screen (LAP-MD)', type: 'IPV Risk Assessment',
        description: 'Take the 11-question Lethality Assessment Program (Maryland Model) — the same instrument used by police and DV advocates nationwide. Get an instant risk read, personalized guidance, and matched safety resources. No account required, no PII saved.',
        url: '/lethality-screen', source: 'Built by Miwa · LAP-MD', urgent: true },
      { id: 'stanley-brown', name: 'Stanley-Brown Safety Planning Intervention', type: 'Safety Planning',
        description: 'The evidence-based 6-step safety planning model. Includes the safety planning guide, training resources, and the Safety Planning App for clients.',
        url: 'https://suicidesafetyplan.com/', source: 'Stanley-Brown Safety Planning' },
      { id: 'safety-plan', name: 'Safety Planning Template (PDF)', type: 'Planning Resource',
        description: 'Free downloadable Stanley-Brown safety plan PDF template. Print-ready template for in-session safety planning — warning signs, internal coping, social contacts, crisis numbers.',
        url: 'https://suicidepreventionlifeline.org/wp-content/uploads/2016/08/Brown_StanleySafetyPlanTemplate.pdf', source: 'AFSP / Brown & Stanley' },
      { id: 'trevor', name: 'The Trevor Project', type: 'LGBTQ+ Youth Crisis',
        description: 'Crisis intervention and suicide prevention for LGBTQ+ youth. TrevorLifeline: 1-866-488-7386. TrevorText: text START to 678-678. TrevorChat available online.',
        url: 'https://www.thetrevorproject.org/', source: 'thetrevorproject.org', urgent: true },
      { id: 'trans-lifeline', name: 'Trans Lifeline', type: 'Trans Community Crisis',
        description: 'Peer support hotline run by and for trans people. US: (877) 565-8860. Canada: (877) 330-6366. Staffed by trans operators who understand specific challenges.',
        url: 'https://translifeline.org/', source: 'translifeline.org', urgent: true },
      { id: 'dv-hotline', name: 'National Domestic Violence Hotline', type: 'Domestic Violence',
        description: '1-800-799-7233 (SAFE). 24/7 confidential support for domestic violence. Also TTY line and online chat. Provides safety planning and local shelter referrals.',
        url: 'https://www.thehotline.org/', source: 'thehotline.org', urgent: true },
      { id: 'rainn', name: 'RAINN (Rape, Abuse & Incest National Network)', type: 'Sexual Violence',
        description: "National Sexual Assault Hotline: 1-800-656-4673. Connects callers to local RAINN affiliate organizations. Also offers online chat and local center directory.",
        url: 'https://www.rainn.org/resources', source: 'rainn.org', urgent: true },
      { id: 'loveisrespect', name: 'loveisrespect (Teen Dating Helpline)', type: 'Teen Dating Violence',
        description: 'Text LOVEIS to 22522 or call 1-866-331-9474. 24/7 confidential support for teens and young adults experiencing dating abuse. Trained advocates, online chat, and safety planning resources.',
        url: 'https://www.loveisrespect.org/', source: 'loveisrespect.org', urgent: true },
      { id: 'human-trafficking', name: 'National Human Trafficking Hotline', type: 'Trafficking',
        description: '1-888-373-7888. Text 233733. 24/7 confidential hotline for reporting tips, requesting services, and asking questions about human trafficking.',
        url: 'https://www.humantraffickinghotline.org', source: 'humantraffickinghotline.org', urgent: true },
      { id: 'childhelp', name: 'Childhelp National Child Abuse Hotline', type: 'Child Abuse',
        description: '1-800-422-4453. 24/7 crisis and referral hotline for child abuse. Professional crisis counselors available. Serves all 50 states, DC, and US territories.',
        url: 'https://childhelphotline.org', source: 'childhelphotline.org', urgent: true },
      { id: 'ncvc', name: 'National Center for Victims of Crime', type: 'Victim Services',
        description: 'Comprehensive resource center for crime victims. Includes referral services, legal rights information, and public policy resources for victim advocacy.',
        url: 'https://victimsofcrime.org', source: 'victimsofcrime.org' },
      { id: 'strengthunited', name: 'StrengthUnited', type: 'Trauma Services',
        description: 'Comprehensive community-based trauma services including crisis intervention, counseling, advocacy, and prevention education for survivors of violence.',
        url: 'https://www.strengthunited.org', source: 'strengthunited.org' },
      { id: 'valor', name: 'ValorUS (CA Sexual Violence Resource)', type: 'Sexual Violence',
        description: "California's primary organization addressing sexual and domestic violence, human trafficking, and other trauma. Includes state rape crisis center directory.",
        url: 'https://www.valor.us', source: 'valor.us' },
      { id: 'redrover', name: 'RedRover Relief (DV Pet Support)', type: 'DV Pet Assistance',
        description: 'Emergency pet boarding and financial assistance for domestic violence survivors with pets. Removes a common barrier to leaving abusive situations.',
        url: 'https://redrover.org/relief-dv/', source: 'redrover.org' },
    ],
  },
  {
    id: 'suicide-prevention',
    category: 'Suicide Prevention & Assessment',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
      </svg>
    ),
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.07)',
    borderColor: 'rgba(249,115,22,0.18)',
    description: 'Suicide risk assessment tools, prevention training, and postvention resources for clinicians.',
    items: [
      { id: 'asq', name: 'Ask Suicide-Screening Questions (ASQ)', type: 'Screening Tool',
        description: 'Free 4-item suicide screening questionnaire for clinical settings. Developed by the National Institutes of Mental Health. High sensitivity for suicide risk.',
        url: 'https://www.nimh.nih.gov/research/research-conducted-at-nimh/asq-toolkit-materials', source: 'NIMH', urgent: true },
      { id: 'sad-persons', name: 'SAD PERSONS Scale', type: 'Risk Assessment',
        description: 'Mnemonic tool (Sex, Age, Depression, Previous attempts, Ethanol, Rational thinking loss, Social support, Organized plan, No spouse, Sickness) for suicide risk evaluation.',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2440316/', source: 'Clinical Research' },
      { id: 'columbia-protocol', name: 'Columbia-Suicide Severity Rating Scale (C-SSRS) Guide', type: 'Risk Assessment',
        description: 'Detailed guide to administering and interpreting the C-SSRS, the most widely used suicide severity rating tool in research and clinical practice.',
        url: 'https://cssrs.columbia.edu/wp-content/uploads/C-SSRS_Scoring_and_Administration_Guide_2022_03_30.pdf', source: 'Columbia University', urgent: true },
      { id: 'afsp-toolkit', name: 'AFSP Suicide Prevention Toolkit', type: 'Multi-Resource',
        description: 'Comprehensive toolkit covering risk factors, warning signs, screening, documentation, and means safety. For clinicians, organizations, and clinical settings.',
        url: 'https://afsp.org/suicide-prevention-toolkit/', source: 'American Foundation for Suicide Prevention' },
      { id: 'postvention', name: 'Postvention & Grief Support', type: 'Support Resource',
        description: 'Resources for supporting individuals after suicide loss. Includes support groups, therapeutic resources, and information for family and friends.',
        url: 'https://www.afsp.org/find-support/we-can-help/support-after-suicide/', source: 'AFSP' },
      { id: 'didi-hirsch', name: 'Didi Hirsch Suicide Prevention Center', type: 'Prevention & Training',
        description: 'Comprehensive suicide prevention services including crisis counseling, training for clinicians and communities, and the 988 LA County call center.',
        url: 'https://didihirsch.org/training/suicide-prevention-training/', source: 'didihirsch.org' },
      { id: 'la-suicide-hotlines', name: 'LA County Suicide Prevention Hotlines', type: 'Hotline Directory',
        description: 'Complete directory of all LA County suicide prevention hotlines with direct phone numbers, hours of operation, and specialty populations served.',
        url: 'http://publichealth.lacounty.gov/suicide_hotlines.htm', source: 'LA County Public Health' },
      { id: 'la-suicide-network', name: 'Los Angeles Suicide Prevention Network', type: 'Community Network',
        description: 'Collaborative network of LA-area organizations working on suicide prevention. Resources, events, training opportunities, and community engagement tools.',
        url: 'http://lasuicidepreventionnetwork.org/', source: 'LA Suicide Prevention Network' },
      { id: 'ca-suicide-prevention', name: 'Each Mind Matters (CA Statewide Campaign)', type: 'Statewide Campaign',
        description: "California's statewide suicide prevention and mental health stigma reduction campaign. Free toolkits, messaging guides, and community engagement resources.",
        url: 'https://www.suicideispreventable.org/', source: 'suicideispreventable.org' },
    ],
  },
  {
    id: 'resource-directories',
    category: 'Resource Directories & Databases',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
    ),
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.07)',
    borderColor: 'rgba(59,130,246,0.18)',
    description: 'Searchable databases of treatment providers, support groups, shelters, and community resources.',
    items: [
      { id: 'samhsa-finder', name: 'SAMHSA Treatment Locator', type: 'Provider Directory',
        description: 'National substance use and mental health treatment facility locator. Search by location for outpatient, residential, and emergency services.',
        url: 'https://findtreatment.samhsa.gov/', source: 'SAMHSA' },
      { id: 'nami-helpline', name: 'NAMI Helpline & Resource Center', type: 'Information & Support',
        description: 'Free helpline (1-800-950-NAMI), support groups, and peer-led programs for individuals and families affected by mental illness.',
        url: 'https://www.nami.org/get-involved/awareness-events/mental-health-awareness-month', source: 'National Alliance on Mental Illness' },
      { id: 'apa-therapist-finder', name: 'APA Psychologist Locator', type: 'Provider Directory',
        description: 'Find licensed psychologists by location, specialty, and insurance. Includes therapist credentials and practice details.',
        url: 'https://locator.apa.org/', source: 'American Psychological Association' },
      { id: 'psychology-today', name: 'Psychology Today Therapist Finder', type: 'Provider Directory',
        description: 'Searchable directory of therapists, counselors, and psychiatrists. Filter by location, specialty, insurance, and virtual availability.',
        url: 'https://www.psychologytoday.com/us/basics/therapy', source: 'Psychology Today' },
      { id: 'support-groups', name: 'NAMI Support Group Locator', type: 'Peer Support',
        description: 'Find peer-led support groups for specific mental health conditions, substance use, bereavement, and other challenges. Includes virtual and in-person options.',
        url: 'https://www.nami.org/Get-Involved/Awareness-Events/Mental-Health-Awareness-Month/Support-Groups', source: 'NAMI' },
      { id: 'one-degree', name: 'One Degree', type: 'Multi-Service Directory',
        description: 'Searchable platform connecting people to social services, food, housing, health, and legal resources. Filter by location, language, and eligibility.',
        url: 'https://www.1degree.org/', source: '1degree.org' },
      { id: 'one-degree-su', name: 'One Degree — StrengthUnited Collections', type: 'Curated Collections',
        description: 'Curated resource collections from StrengthUnited on One Degree. Pre-filtered lists of vetted local services for trauma survivors and families.',
        url: 'https://www.1degree.org/collections?page=org&organization_id=5979', source: '1degree.org / StrengthUnited' },
      { id: 'findhelp', name: 'FindHelp', type: 'Multi-Service Directory',
        description: 'Zip-code-based search for free and reduced-cost programs: food, housing, health, transportation, legal aid, and more. Used by many health systems for SDOH referrals.',
        url: 'https://www.findhelp.org', source: 'findhelp.org' },
      { id: '211la', name: '211 LA County', type: 'County Referral Service',
        description: 'LA County resource and referral hub. Searchable directory of health, human, and social services. Also call 211 for live assistance in 150+ languages.',
        url: 'https://211la.org/resources/search', source: '211la.org' },
      { id: 'valor-directory', name: 'VALOR Rape Crisis Center Directory', type: 'CA Service Directory',
        description: "Directory of California's rape crisis centers with locations, contact information, and services offered. Find local advocacy and counseling services by region.",
        url: 'https://www.valor.us/get-help/get-help-california/', source: 'valor.us' },
      { id: 'cpedv', name: 'CPEDV DV Center Directory', type: 'CA Service Directory',
        description: "California Partnership to End Domestic Violence. Statewide directory of DV service providers with shelter, counseling, legal, and children's program listings.",
        url: 'https://cpedv.org/find-help/', source: 'cpedv.org' },
      { id: 'sfv-bulletin', name: 'SFV Community Resource Bulletin Board', type: 'Community Board',
        description: 'San Fernando Valley community resource board with current service listings, event announcements, and referral information maintained by local organizations.',
        url: 'https://padlet.com/SFCity/communityresourcebulletinboard', source: 'SFV Community' },
      { id: 'lawhelpca', name: 'LawHelpCA — Free Legal Aid Directory', type: 'Legal Aid',
        description: 'California-wide directory of free and low-cost legal aid programs. Filter by topic (family, housing, immigration, public benefits) and county. Especially useful for survivor referrals.',
        url: 'https://www.lawhelpca.org/', source: 'lawhelpca.org' },
      { id: 'lacba', name: 'LA County Bar Association — Lawyer Referral', type: 'Attorney Referral',
        description: 'State Bar–certified lawyer referral service for Los Angeles County. Connect clients with vetted attorneys for low-cost initial consultations across most practice areas.',
        url: 'https://www.lacba.org/', source: 'lacba.org' },
    ],
  },
  {
    id: 'victim-survivor',
    category: 'Victim & Survivor Services',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
      </svg>
    ),
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.07)',
    borderColor: 'rgba(139,92,246,0.18)',
    description: 'Legal rights, victim compensation, protective orders, mandated reporting, and advocacy resources for survivors.',
    items: [
      { id: 'nova', name: 'National Organization for Victim Assistance (NOVA)', type: 'Victim Advocacy',
        description: 'Resources and referrals for crime victims, including counseling, legal support, and compensation information. Directory of local victim service providers.',
        url: 'https://www.trynova.org/', source: 'NOVA' },
      { id: '1in6', name: '1in6 — Male Sexual Abuse Survivors', type: 'Survivor Support',
        description: 'Resources and support for male survivors of childhood sexual abuse. Includes educational materials, survivor stories, clinician resources, and peer support for men healing from abuse.',
        url: 'https://1in6.org/', source: '1in6.org' },
      { id: 'stalking-resources', name: 'National Center for Victims of Crime — Stalking Resource Center', type: 'Victim Support',
        description: 'Comprehensive stalking education, safety planning, and legal resources. Includes guidance for clinicians supporting stalking survivors.',
        url: 'https://www.victimsofcrime.org/our-programs/stalking-resource-center/', source: 'National Center for Victims of Crime' },
      { id: 'lapd-station-finder', name: 'LAPD — Find Your Local Police Station', type: 'Report a Crime',
        description: 'Locate the nearest Los Angeles Police Department station to where the incident occurred. Useful for clients who need to file a police report, request records, or access in-person victim services. Los Angeles residents only.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'doj-kit-tracking', name: 'DOJ Survivor Portal (Kit Tracking)', type: 'Forensic Evidence',
        description: 'California Department of Justice portal for sexual assault kit tracking. Survivors can check the status of their forensic evidence kit through this secure system.',
        url: 'https://kitstatus.doj.ca.gov/', source: 'CA Dept of Justice' },
      { id: 'vinelink', name: 'VINE Link (Custody & Case Info)', type: 'Victim Notification',
        description: "National victim notification network. Register to receive automated alerts about changes in an offender's custody status, court dates, and case proceedings.",
        url: 'https://vinelink.com/', source: 'vinelink.com' },
      { id: 'calvcb', name: 'California Victim Compensation Board', type: 'Financial Assistance',
        description: 'CalVCB helps crime victims pay for expenses related to violent crime: medical/dental treatment, mental health counseling, income loss, relocation, and funeral costs.',
        url: 'https://victims.ca.gov/', source: 'CA Victim Compensation Board' },
      { id: 'victims-assistance', name: 'LA Victims Assistance Program', type: 'Victim Advocacy',
        description: 'Free assistance for crime victims in Los Angeles including crisis intervention, case advocacy, court accompaniment, emergency assistance, and referral services.',
        url: 'https://www.helplacrimevictims.org/#/homepage', source: 'helplacrimevictims.org' },
      { id: 'restraining-orders', name: 'Civil Protection / Restraining Orders', type: 'Legal Protection',
        description: "California courts self-help guide for obtaining domestic violence, civil harassment, elder abuse, and workplace violence restraining orders. Step-by-step filing instructions.",
        url: 'https://selfhelp.courts.ca.gov/restraining-orders', source: 'CA Courts Self-Help' },
      { id: 'marsys-law', name: "Marsy's Law Victim Rights", type: 'Legal Rights',
        description: "Information about Marsy's Law victim rights in California including the right to notification, restitution, protection, and participation in criminal proceedings.",
        url: 'https://www.oag.ca.gov/victimservices/marsys_law', source: 'CA Attorney General' },
      { id: 'ag-victim-services', name: 'CA Attorney General Victim Services Unit', type: 'State Resources',
        description: "Comprehensive victim services from the California AG's office including sexual violence resources, victim advocacy, restitution assistance, and legal rights information.",
        url: 'https://www.oag.ca.gov/victimservices', source: 'CA Attorney General' },
      { id: 'safe-at-home', name: 'Safe at Home Program', type: 'Address Confidentiality',
        description: "California Secretary of State's address confidentiality program for survivors of DV, stalking, sexual assault, and trafficking. Provides substitute mailing address.",
        url: 'https://www.sos.ca.gov/safeathome/', source: 'CA Secretary of State' },
      { id: 'civil-rights-dept', name: 'Civil Rights Department (Workplace)', type: 'Workplace Accommodations',
        description: "California Civil Rights Department. File workplace discrimination complaints, learn about reasonable accommodations for survivors, and access employment protection info.",
        url: 'https://calcivilrights.ca.gov/complaintprocess', source: 'CA Civil Rights Dept' },
      { id: 'dcfs-cares', name: 'DCFS Child Abuse Reporting (CARES)', type: 'Mandated Reporting',
        description: 'Online mandated reporting system for suspected child abuse and neglect in Los Angeles County. For mandated reporters to file DCFS reports electronically.',
        url: 'https://mandreptla.org/cars.web/', source: 'LA County DCFS', urgent: true },
      { id: 'aps', name: 'Adult Protective Services (APS)', type: 'Mandated Reporting',
        description: 'Report suspected abuse, neglect, or exploitation of dependent adults and elders. Includes state APS info and ReportToAPS.org for online reporting guidance.',
        url: 'https://www.cdss.ca.gov/inforesources/adult-protective-services', source: 'CA Dept of Social Services', urgent: true },
    ],
  },
  {
    id: 'housing-shelter',
    category: 'Housing & Shelter Resources',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
    ),
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.07)',
    borderColor: 'rgba(14,165,233,0.18)',
    description: 'Emergency housing, DV shelters, transitional housing, voucher programs, and safe parking.',
    items: [
      { id: 'chirp-la', name: 'CHIRP LA Housing Resource Guides', type: 'Resource Hub',
        description: 'Comprehensive housing resource guides from CHIRP LA. Regularly updated directories of shelters, transitional housing, permanent supportive housing, and safe parking.',
        url: 'https://chirpla.org/helpful-resources', source: 'chirpla.org' },
      { id: 'chirp-emergency', name: 'CHIRP LA Emergency Housing Guide', type: 'Emergency Shelter',
        description: 'Current emergency housing options in Los Angeles County including shelters, hotel voucher programs, and emergency bed availability. Updated regularly.',
        url: 'https://chirpla.org/hubfs/Emergency%20February%202026.pdf', source: 'CHIRP LA', urgent: true },
      { id: 'chirp-dv-shelters', name: 'CHIRP LA DV Shelter Directory', type: 'DV Shelters',
        description: 'Directory of domestic violence shelters in greater Los Angeles with intake phone numbers, bed availability, services offered, and population served.',
        url: 'https://chirpla.org/hubfs/Domestic%20Violence%20March%202026.pdf', source: 'CHIRP LA', urgent: true },
      { id: 'chirp-safe-parking', name: 'Safe Parking Program Guide', type: 'Safe Parking',
        description: 'Guide to safe parking programs for individuals and families living in vehicles. Includes locations, eligibility, hours of operation, and available support services.',
        url: 'https://chirpla.org/hubfs/Safe%20Parking-fy2025-2026-2.pdf', source: 'CHIRP LA' },
      { id: 'safe-parking-referral', name: 'Safe Parking Referral Form', type: 'Referral Form',
        description: 'Online referral form for safe parking programs. Clinicians and case managers can submit referrals directly for clients needing safe overnight parking.',
        url: 'https://forms.office.com/r/nz7DDZMZu0', source: 'LA County' },
      { id: 'chirp-transitional', name: 'Transitional Housing Directory', type: 'Transitional Housing',
        description: 'Directory of transitional housing programs in LA County. Includes program length, eligibility criteria, services provided, and intake process for each facility.',
        url: 'https://chirpla.org/hubfs/March%202026%20Transitional%20House.pdf', source: 'CHIRP LA' },
      { id: 'door-of-hope', name: 'Door of Hope Intake', type: 'Family Housing',
        description: 'Transitional housing and comprehensive support services for families experiencing homelessness. Includes case management, employment support, and childcare.',
        url: 'https://doorofhope.us/resources/', source: 'doorofhope.us' },
      { id: 'housing-choice', name: 'HUD Housing Choice Voucher Program', type: 'Housing Assistance',
        description: 'Federal program providing rental assistance for low-income families and individuals. Includes links to local housing authorities and eligibility information.',
        url: 'https://www.hud.gov/program_offices/public_indian_housing/programs/ph/phr/about/fact_sheet', source: 'U.S. Dept of Housing and Urban Development' },
      { id: 'homeless-hotline', name: 'National Homeless Shelter Directory', type: 'Emergency Shelter',
        description: 'Searchable directory to locate emergency shelters and housing assistance in any location. Phone and directory search available.',
        url: 'https://www.homelessshelterdirectory.org/', source: 'Homeless Shelter Directory' },
      { id: 'hud-resources', name: 'HUD Homeless Assistance Programs', type: 'Housing Support',
        description: 'Comprehensive information on federal homeless services, CoC programs, and local resources. Information for individuals and service providers.',
        url: 'https://www.hud.gov/program_offices/special_needs_assistance_programs/homeless_assistance_programs', source: 'HUD' },
      { id: 'housing-resources', name: 'NAMI Housing & Supportive Services', type: 'Housing Support',
        description: 'NAMI resources for stable housing as part of recovery. Includes guidance for individuals and families seeking housing for someone with mental illness.',
        url: 'https://www.nami.org/Get-Involved/Awareness-Events/Mental-Health-Awareness-Month/Get-Involved', source: 'NAMI' },
      { id: 'new-economics-for-women', name: 'New Economics for Women (NEW)', type: 'Housing & Economic Empowerment',
        description: 'Nonprofit providing affordable housing, financial literacy, workforce development, childcare, and support services for women and families — with a focus on Latina communities and domestic violence survivors. Based in Los Angeles.',
        url: 'https://neweconomicsforwomen.org/', source: 'New Economics for Women' },
    ],
  },
  {
    id: 'trauma-education',
    category: 'Trauma Education & Training',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
      </svg>
    ),
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.07)',
    borderColor: 'rgba(168,85,247,0.18)',
    description: 'Trauma-informed training, ACEs education, prevention resources, and professional development for clinicians and community workers.',
    items: [
      { id: 'nctsn', name: 'National Child Traumatic Stress Network (NCTSN)', type: 'Child Trauma',
        description: 'Comprehensive child trauma resources including assessment tools, treatment protocols, training materials, and family resources. Funded by SAMHSA.',
        url: 'https://www.nctsn.org', source: 'nctsn.org' },
      { id: 'istss', name: 'International Society for Traumatic Stress Studies (ISTSS)', type: 'Professional Organization',
        description: 'Resources for treating trauma, dissociative disorders, and complex PTSD. Annual conference, peer-reviewed journal, and training programs.',
        url: 'https://www.isstd.org/', source: 'ISSTD' },
      { id: 'trauma-center', name: 'Trauma Center (Bessel van der Kolk)', type: 'Training & Research',
        description: 'Research and training on trauma neurobiology and treatment. Focuses on somatic and neuroscience-informed approaches to trauma.',
        url: 'https://traumacenter.org/', source: 'Trauma Center' },
      { id: 'tri', name: 'Trauma Resource Institute', type: 'Training & Certification',
        description: 'Community Resiliency Model (CRM) and Trauma Resiliency Model (TRM) training. Evidence-based biological approaches to trauma treatment and resilience building.',
        url: 'https://www.traumaresourceinstitute.com', source: 'traumaresourceinstitute.com' },
      { id: 'paces-connection', name: 'PACEs Connection', type: 'ACEs Education',
        description: 'Network and resource hub for Positive and Adverse Childhood Experiences (PACEs) science. Resources on ACEs screening, trauma-informed systems, and resilience-building practices.',
        url: 'https://www.pacesconnection.com/', source: 'PACEs Connection' },
      { id: 'see-learning', name: 'Emory SEE Learning (Social, Emotional & Ethical Learning)', type: 'Curriculum & Training',
        description: 'Evidence-based K–12 curriculum from Emory University integrating mindfulness, compassion training, and systems thinking. Useful for clinicians working with schools, adolescents, or adapting SEL frameworks to therapy.',
        url: 'https://www.seelearning.emory.edu', source: 'Emory University' },
      { id: 'manual-de-autocuidado', name: 'Manual de Autocuidado', type: 'Spanish Self-Care Manual',
        description: 'Spanish-language self-care manual for psychoeducation, coping skills, resilience planning, and client-facing wellness exercises.',
        url: '/resources/manual-de-autocuidado.pdf', source: 'Uploaded Spanish PDF' },
      { id: 'greater-good', name: 'Greater Good in Education (Berkeley)', type: 'Well-Being Science',
        description: 'Science-based practices for well-being from UC Berkeley. Evidence-based activities, articles, and tools for fostering kindness, gratitude, resilience, and mindfulness.',
        url: 'https://ggia.berkeley.edu/', source: 'UC Berkeley' },
      { id: 'evawi', name: 'End Violence Against Women International', type: 'Professional Training',
        description: 'Training and technical assistance for professionals responding to gender-based violence. Start by Believing campaign, online training institute, and best practices.',
        url: 'http://www.evawintl.org', source: 'evawintl.org' },
      { id: 'start-by-believing', name: 'Start by Believing', type: 'Response Campaign',
        description: 'Public awareness campaign promoting a victim-centered approach to sexual assault response. Includes training materials, event toolkits, and professional guidelines.',
        url: 'https://www.startbybelieving.org', source: 'EVAWI' },
      { id: 'polaris', name: 'Polaris Project (Trafficking Signs)', type: 'Trafficking Prevention',
        description: 'Tools for recognizing signs of human trafficking in clinical and community settings. Includes screening questions, red flags, and reporting guidance for clinicians.',
        url: 'https://polarisproject.org/human-trafficking/recognize-signs', source: 'Polaris Project' },
      { id: 'know-your-ix', name: 'Know Your IX', type: 'Title IX Rights',
        description: 'Guide to Title IX rights for survivors of campus sexual violence. Resources for students, advocates, and clinicians working with college-age populations.',
        url: 'https://www.knowyourix.org', source: 'knowyourix.org' },
      { id: 'stopitnow', name: 'Stop It Now!', type: 'Abuse Prevention',
        description: 'Prevention resources for child sexual abuse. Includes warning signs, conversation guides for families, and a confidential helpline (1-888-773-8368) for adults concerned about behavior.',
        url: 'https://www.stopitnow.org', source: 'stopitnow.org' },
      { id: 'atsa', name: 'Association for Treatment of Sexual Abusers (ATSA)', type: 'Offender Treatment',
        description: 'Professional resources for the treatment and management of individuals who have sexually abused. Research, practice guidelines, and provider directory.',
        url: 'http://www.atsa.com', source: 'atsa.com' },
      { id: 'without-my-consent', name: 'Without My Consent', type: 'Image-Based Abuse',
        description: 'Resources for victims of non-consensual intimate image sharing. Includes legal guides, takedown request templates, and state law information.',
        url: 'http://www.withoutmyconsent.org', source: 'withoutmyconsent.org' },
      { id: 'naspc', name: 'North American Society for Psychotherapy & Counseling (NASPC)', type: 'Professional Organization',
        description: 'Network of trauma specialists offering training, consultation, and professional development in trauma-informed care.',
        url: 'https://naspc.org/', source: 'NASPC' },
      { id: 'resilience-coalition', name: 'International Trauma Resilience Coalition', type: 'Resilience Building',
        description: 'International coalition focused on building personal and organizational resilience in the face of adversity. Resources, research, and community of practice for practitioners.',
        url: 'http://www.theresourceinnovationgroup.org/intl-tr-coalition', source: 'Resource Innovation Group' },
    ],
  },
  {
    id: 'la-county-hotlines',
    category: 'Los Angeles County 24/7 Hotlines',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
      </svg>
    ),
    color: '#dc2626',
    bgColor: 'rgba(220,38,38,0.06)',
    borderColor: 'rgba(220,38,38,0.2)',
    description: 'Direct-dial LA County crisis lines — DV, sexual assault, mental health, child abuse, elder abuse, substance use, youth crisis. Keep visible during sessions.',
    items: [
      { id: 'la-dmh-access', name: 'LA County DMH ACCESS Line (Mental Health)', type: 'Mental Health Crisis',
        description: '(800) 854-7771. 24/7 LA County Department of Mental Health helpline. Crisis support, mental-health screening, and direct connection to county-funded services. Multilingual.',
        url: 'https://dmh.lacounty.gov/get-help-now/', source: 'LA County DMH', urgent: true },
      { id: 'la-dcfs-child', name: 'LA County DCFS — Child Protection Hotline', type: 'Child Abuse Reporting',
        description: '(800) 540-4000. 24/7 LA County Department of Children & Family Services hotline for reporting suspected child abuse or neglect. Mandated reporters: file reports here.',
        url: 'https://dcfs.lacounty.gov/parents/how-do-i/report-child-abuse/', source: 'LA County DCFS', urgent: true },
      { id: 'la-aps-hotline', name: 'LA County APS — Disabled Adult / Elder Abuse', type: 'Elder Abuse Reporting',
        description: '(800) 540-4000. 24/7 LA County Adult Protective Services hotline for reporting suspected abuse, neglect, or exploitation of dependent adults and elders. Mandated reporters file here.',
        url: 'https://wdacs.lacounty.gov/services/aps/', source: 'LA County APS', urgent: true },
      { id: 'la-dv-hotline', name: 'LA County Domestic Violence Hotline', type: 'Domestic Violence',
        description: '(800) 978-3600. 24/7 LA County DV hotline. Crisis support, safety planning, shelter referrals, and connection to local DV agencies.',
        url: 'https://dpss.lacounty.gov/en/health/domestic-violence.html', source: 'LA County DPSS', urgent: true },
      { id: 'pov-hotline', name: 'Peace Over Violence — Battery & Sexual Assault', type: '24/7 Crisis Line',
        description: '(310) 392-8381 / (213) 626-3393. 24/7 hotline for battered persons, sexual assault, and stalking. Walk-in advocacy available. Address: 1541 Wilshire Blvd., Suite 300, Los Angeles, CA 90017. In-custody dial *25.',
        url: 'https://www.peaceoverviolence.org/', source: 'Peace Over Violence', urgent: true },
      { id: 'la-sexual-assault', name: 'LA County Sexual Assault Hotline', type: 'Sexual Assault',
        description: '(877) 943-5778. 24/7 county sexual assault crisis line for survivors, family members, and clinicians. Connection to local rape crisis centers and SART services.',
        url: 'https://valor.us/get-help/get-help-california/', source: 'LA County / VALOR', urgent: true },
      { id: 'la-substance-helpline', name: 'LA County Substance Use Helpline', type: 'Substance Use',
        description: '(800) 564-6600. 24/7 LA County Department of Public Health Substance Abuse Service helpline. Treatment referrals, crisis support, and access to county-funded SUD services.',
        url: 'http://publichealth.lacounty.gov/sapc/', source: 'LA County DPH SAPC', urgent: true },
      { id: 'ca-youth-crisis', name: 'California Youth Crisis Line', type: 'Youth Crisis',
        description: '(800) 843-5200. 24/7 statewide crisis line for youth ages 12–24 and their families. Crisis counseling, safe-place referrals, and family reunification support.',
        url: 'https://calyouth.org/cycl/', source: 'California Youth Crisis Line', urgent: true },
      { id: 'la-victims-resource', name: 'LA Victims of Crime Resource Center', type: 'Victim Resource Line',
        description: '(800) 842-5200. Information, referrals, and crisis support for crime victims in Los Angeles County. Includes guidance on rights, compensation, and protective orders.',
        url: 'https://www.helplacrimevictims.org/', source: 'helplacrimevictims.org', urgent: true },
      { id: 'strength-united-line', name: 'Strength United (Van Nuys)', type: '24/7 Crisis Line',
        description: '(818) 787-9750. 24/7 trauma response line covering San Fernando Valley and surrounding communities. In-custody dial *26. Address: 14651 Oxnard St., Van Nuys, CA 91411.',
        url: 'https://www.strengthunited.org/', source: 'Strength United', urgent: true },
    ],
  },
  {
    id: 'la-law-enforcement',
    category: 'Los Angeles Law Enforcement & Reporting',
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.75} d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
      </svg>
    ),
    color: '#0f766e',
    bgColor: 'rgba(15,118,110,0.07)',
    borderColor: 'rgba(15,118,110,0.18)',
    description: 'LA Sheriff, LAPD, PREA reporting, Crime Stoppers, SART centers, and the Family Justice Center. For when a client needs to report or interact with law enforcement.',
    items: [
      { id: 'lasd-main', name: 'LA County Sheriff\'s Department (LASD)', type: 'Sheriff Main',
        description: 'Primary website for the LA County Sheriff\'s Department. Station locator, reporting options, inmate information, and victim services.',
        url: 'https://lasd.org/', source: 'lasd.org' },
      { id: 'lasd-prea', name: 'LASD — PREA Coordinator (Custody Sexual Abuse)', type: 'PREA Reporting',
        description: 'Email prea-coordinator@lasd.org to report sexual abuse or harassment in LASD custody under the Prison Rape Elimination Act. Mailing: Office of PREA Compliance, 4700 Ramona Blvd., Monterey Park, CA 91754.',
        url: 'mailto:prea-coordinator@lasd.org', source: 'LASD PREA Compliance', urgent: true },
      { id: 'la-crime-stoppers', name: 'LA Crime Stoppers — Anonymous Tip Line', type: 'Anonymous Reporting',
        description: '(800) 222-8477. Anonymous tip line covering LA County. Custody facility callers can dial 21 from a custody facility phone to report privately.',
        url: 'https://lacrimestoppers.org/', source: 'lacrimestoppers.org' },
      { id: 'lasd-sart', name: 'LASD SART Centers (Sexual Assault Response)', type: 'Forensic Exam',
        description: 'Sexual Assault Response Team centers for forensic exams in LA County. Basin (Central LA): (213) 760-8728. North (Antelope Valley/SCV): (213) 247-2724. SART Roster Reference No. 508.1.',
        url: 'https://lasd.org/', source: 'LASD SART', urgent: true },
      { id: 'la-family-justice', name: 'LA Family Justice Center (Van Nuys)', type: 'Multi-Service Hub',
        description: '(818) 933-9497. One-stop hub colocating advocacy, legal aid, law enforcement, and counseling for DV, sexual assault, child abuse, elder abuse, and human trafficking survivors. 14651 Oxnard St., Van Nuys, CA 91411.',
        url: 'https://lacityattorney.org/family-justice-center', source: 'LA City Attorney' },
      { id: 'lapd-central', name: 'LAPD Central Division', type: 'LAPD Branch',
        description: '(213) 486-0765. 251 E. 6th St., Los Angeles, CA 90014. Files reports for incidents in downtown LA.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'lapd-southwest', name: 'LAPD Southwest Division', type: 'LAPD Branch',
        description: '(213) 369-1617. 1546 W. Martin Luther King Blvd., Los Angeles, CA 90062.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'lapd-southeast', name: 'LAPD Southeast Division', type: 'LAPD Branch',
        description: '(213) 972-1045. 145 W. 108th St., Los Angeles, CA 90061.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'lapd-west-valley', name: 'LAPD West Valley Division', type: 'LAPD Branch',
        description: '(818) 374-7849. 19020 Vanowen St., Reseda, CA 91335.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'lapd-west-la', name: 'LAPD West LA Division', type: 'LAPD Branch',
        description: '(310) 444-1534. 1663 Butler Ave., Los Angeles, CA 90025.',
        url: 'https://www.lapdonline.org/find-your-local-police-station/', source: 'LAPD' },
      { id: 'la-vap-central', name: 'LA Victim Assistance Program (VAP) — Central Office', type: 'Victim Advocacy',
        description: '(213) 978-4537 · TDD (213) 978-8310 · Fax (213) 482-6544. 221 N. Figueroa St., Suite 100, LA, CA 90012. Crisis intervention, court accompaniment, restitution help, and emergency assistance for crime victims. Also available via the VAP mobile app on iOS/Android.',
        url: 'https://www.helplacrimevictims.org/', source: 'helplacrimevictims.org' },
      { id: 'la-emergency-line', name: 'City of LA Emergency / Non-Emergency Lines', type: 'City Services',
        description: 'Emergency: 911 or (866) 613-3777. Non-emergency county services: 311 or (213) 974-1234. Use non-emergency for noise complaints, service requests, and general info.',
        url: 'https://my.lacity.gov/myla311', source: 'City of LA / LA County' },
    ],
  },
]
